// MediaFileSource integration tests - driven by the deterministic corpus
// (loop/local/fixed_clips/corpus/translation_1080p60.mp4, 600 frames, 60fps).
// Verifies the contract translation layer: open metadata, monotonic PTS in
// the real stream time base, honest color defaults, atomic seek protocol,
// and EOS drain. Requires the corpus (generated by veyra_clip_gen).
#include <cstdio>
#include <string>

#include "veyra/source/MediaFileSource.h"

using namespace veyra;
using namespace veyra::source;

namespace {

int g_checks = 0;
int g_failures = 0;

void check(const char* name, bool ok) {
    ++g_checks;
    if (!ok) { ++g_failures; std::printf("  [FAIL] %s\n", name); }
    else { std::printf("  [PASS] %s\n", name); }
}

} // namespace

int main(int argc, char** argv) {
    std::wstring clip = L"loop/local/fixed_clips/corpus/translation_1080p60.mp4";
    if (argc > 1) {
        clip.assign(argv[1], argv[1] + std::strlen(argv[1]));
    }

    std::printf("source-file: open + metadata\n");
    MediaFileSource src;
    SourceOpenDesc desc;
    desc.path = clip;
    desc.preferHardwareDecode = false; // contract test: software decode, no GPU needed
    if (!src.open(desc)) {
        std::printf("source-file: open FAILED (corpus missing? run veyra_clip_gen --make-corpus)\n");
        return 1;
    }
    const SourceInfo& info = src.info();
    check("open:extent", info.width == 1920 && info.height == 1080);
    check("open:kind", info.kind == pipeline::SourceKind::File);
    check("open:duration", info.duration.known && info.duration.toDouble() > 9.0 && info.duration.toDouble() < 11.0);
    check("open:fps-nominal-60", info.averageFps > 59.0 && info.averageFps < 61.0);
    // 1080p SDR H.264 with no color metadata: BT.709 limited assumed (Playbook 9).
    check("open:color-matrix-709-assumed",
        info.color.matrix == pipeline::YuvMatrix::BT709 && info.color.matrixAssumed);
    check("open:color-range-limited-assumed",
        info.color.range == pipeline::ColorRange::Limited && info.color.rangeAssumed);
    check("open:not-hdr", !info.color.isHdrPath());

    std::printf("source-file: read 90 frames (PTS monotonic, flags)\n");
    pipeline::FramePacket p;
    const AVFrame* frame = nullptr;
    bool first = true;
    double lastPts = -1.0;
    int monotonicViolations = 0;
    int frames = 0;
    for (int i = 0; i < 90; ++i) {
        const SourceReadStatus st = src.read(p, &frame);
        if (st != SourceReadStatus::Frame) { break; }
        ++frames;
        if (first) {
            check("read:first-open-flag", (p.flags & static_cast<uint32_t>(pipeline::FrameFlagBits::Open)) != 0);
            check("read:first-frame-nonnull", frame != nullptr);
            first = false;
        }
        if (p.pts.known && p.pts.toDouble() <= lastPts) { ++monotonicViolations; }
        if (p.pts.known) { lastPts = p.pts.toDouble(); }
        if (!p.duration.known) { break; }
    }
    check("read:90-frames", frames == 90);
    check("read:pts-monotonic", monotonicViolations == 0);
    check("read:duration-known", p.duration.known && p.duration.toDouble() > 0.0);
    check("read:sequence-monotonic", p.sequence == 90);

    std::printf("source-file: atomic seek to 5s\n");
    const uint64_t epochBefore = src.epoch();
    check("seek:accepted", src.seek(pipeline::Rational{5, 1}));
    const SourceReadStatus st = src.read(p, &frame);
    check("seek:frame-after", st == SourceReadStatus::Frame);
    check("seek:flag-set", (p.flags & static_cast<uint32_t>(pipeline::FrameFlagBits::Seek)) != 0);
    check("seek:epoch-advanced", src.epoch() == epochBefore + 1 && p.sourceEpoch == epochBefore + 1);
    check("seek:pts-at-or-after-target", p.pts.known && p.pts.toDouble() >= 4.9 && p.pts.toDouble() < 6.0);
    SourceReadStatus st2 = src.read(p, &frame);
    check("seek:next-frame-no-flag", st2 == SourceReadStatus::Frame
        && (p.flags & static_cast<uint32_t>(pipeline::FrameFlagBits::Seek)) == 0);

    std::printf("source-file: drain to EOS\n");
    int drained = 0;
    for (;;) {
        const SourceReadStatus st3 = src.read(p, &frame);
        if (st3 == SourceReadStatus::Eos) { break; }
        if (st3 == SourceReadStatus::Error) { break; }
        ++drained;
        if (drained > 1000) { break; } // safety
    }
    check("eos:reached", drained < 1000);
    // 90 initial + 2 post-seek + drained remainder; seek to 5s of a 10s clip
    // leaves roughly half the frames to drain.
    const uint64_t expectedTotal = 90 + 2 + static_cast<uint64_t>(drained);
    check("eos:total-accounted", src.framesRead() == expectedTotal);
    check("eos:drained-roughly-half", drained >= 200 && drained <= 500);

    src.close();
    check("close:info-cleared", !src.info().opened);

    std::printf("source-file: %d checks, %d failures\n", g_checks, g_failures);
    return g_failures == 0 ? 0 : 1;
}
